# Dependencies
markdown:         kramdown
# highlighter:      pygments

# plugins:
#   - jekyll-gist
#   - jekyll-paginate

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Arne F. Meyer
tagline:          'Studying the (visual) brain in action'
description:      'Studying the (visual) brain in action'
url:              http://arnefmeyer.github.io
baseurl:          /

author:
  name:           'Arne F. Meyer'
  url:            http://arnefmeyer.github.io

paginate:         5

# excerpt_separator: "<!--more-->"
exclude:
  - public/images/*.svg


# Custom vars
version:          1

github:
  repo:           http://www.github.com/arnefmeyer

github: [metadata]
