# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Arne F. Meyer
tagline:          'Studying the (visual) brain in action'
description:      'Studying the (visual) brain in action'
url:              http://arnefmeyer.github.io
baseurl:          ''

author:
  name:           'Arne F. Meyer'
  url:            http://arnefmeyer.github.io

paginate:         5

# excerpt_separator: "<!--more-->"
exclude:
  - public/images/*.svg


# Custom vars
version:          1

github:
  repo:           https://github.com/arnefmeyer/arnefmeyer.github.io

github: [metadata]
