name: Arne F. Meyer -- Studying the (visual) brain in action
description: Research page
author: Arne F. Meyer
email: a1.meyer@donders.ru.nl

#baseurl: '/Arcana-Jekyll-Theme'
baseurl: ''

# Build settings
markdown: kramdown

#gems:
#- jekyll-email-protect

# collections
collections:
  oeplugins:
    order:
      - oeplugin-framegrabber.md
      - oeplugin-rpicamera.md
      - oeplugin-imureader.md
      - oeplugin-virtualref.md
      - oeplugin-eventpublisher.md
  srf:
    output: true
  misc:
    output: true
